# Generated by Django 5.0.4 on 2024-06-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок блога', max_length=100, verbose_name='Заголовок')),
                ('slug', models.CharField(help_text='Сгенерируется автоматически из заголовка', max_length=100, verbose_name='Ссылка')),
                ('content', models.TextField(help_text='Введите текст блога', verbose_name='Содержание')),
                ('preview_picture', models.ImageField(blank=True, help_text='Загрузите превью изображение', null=True, upload_to='blog/photo', verbose_name='Превью изображение')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Создано автоматически', verbose_name='Дата создания')),
                ('published_sign', models.BooleanField(default=False, help_text='Отметьте, если блог опубликован', verbose_name='Опубликовано')),
                ('views_counter', models.PositiveIntegerField(default=0, help_text='Счетчик просмотров', verbose_name='Количество просмотров')),
            ],
        ),
    ]
