# Generated by Django 5.0.4 on 2024-04-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('title', models.TextField(max_length=150, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('title', models.TextField(max_length=150, verbose_name='Описание')),
                ('picture', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('cost', models.IntegerField(verbose_name='Цена за штуку')),
                ('date_of_create', models.DateField(verbose_name='Дата создания')),
                ('last_modified_date', models.DateField(verbose_name='Дата последнего изменения')),
            ],
        ),
    ]
